/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayersIndexRouteImport } from './routes/players.index'
import { Route as PlayersIdRouteImport } from './routes/players.$id'
import { Route as MatchesNewRouteImport } from './routes/matches.new'
import { Route as MatchesIdRouteImport } from './routes/matches.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIdRoute = PlayersIdRouteImport.update({
  id: '/players/$id',
  path: '/players/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesNewRoute = MatchesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MatchesRoute,
} as any)
const MatchesIdRoute = MatchesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MatchesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/awards': typeof AwardsRoute
  '/matches': typeof MatchesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/matches/$id': typeof MatchesIdRoute
  '/matches/new': typeof MatchesNewRoute
  '/players/$id': typeof PlayersIdRoute
  '/players/': typeof PlayersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/awards': typeof AwardsRoute
  '/matches': typeof MatchesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/matches/$id': typeof MatchesIdRoute
  '/matches/new': typeof MatchesNewRoute
  '/players/$id': typeof PlayersIdRoute
  '/players': typeof PlayersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/awards': typeof AwardsRoute
  '/matches': typeof MatchesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/matches/$id': typeof MatchesIdRoute
  '/matches/new': typeof MatchesNewRoute
  '/players/$id': typeof PlayersIdRoute
  '/players/': typeof PlayersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/awards'
    | '/matches'
    | '/sitemap.xml'
    | '/matches/$id'
    | '/matches/new'
    | '/players/$id'
    | '/players/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/awards'
    | '/matches'
    | '/sitemap.xml'
    | '/matches/$id'
    | '/matches/new'
    | '/players/$id'
    | '/players'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/awards'
    | '/matches'
    | '/sitemap.xml'
    | '/matches/$id'
    | '/matches/new'
    | '/players/$id'
    | '/players/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AwardsRoute: typeof AwardsRoute
  MatchesRoute: typeof MatchesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PlayersIdRoute: typeof PlayersIdRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$id': {
      id: '/players/$id'
      path: '/players/$id'
      fullPath: '/players/$id'
      preLoaderRoute: typeof PlayersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/new': {
      id: '/matches/new'
      path: '/new'
      fullPath: '/matches/new'
      preLoaderRoute: typeof MatchesNewRouteImport
      parentRoute: typeof MatchesRoute
    }
    '/matches/$id': {
      id: '/matches/$id'
      path: '/$id'
      fullPath: '/matches/$id'
      preLoaderRoute: typeof MatchesIdRouteImport
      parentRoute: typeof MatchesRoute
    }
  }
}

interface MatchesRouteChildren {
  MatchesIdRoute: typeof MatchesIdRoute
  MatchesNewRoute: typeof MatchesNewRoute
}

const MatchesRouteChildren: MatchesRouteChildren = {
  MatchesIdRoute: MatchesIdRoute,
  MatchesNewRoute: MatchesNewRoute,
}

const MatchesRouteWithChildren =
  MatchesRoute._addFileChildren(MatchesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AwardsRoute: AwardsRoute,
  MatchesRoute: MatchesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PlayersIdRoute: PlayersIdRoute,
  PlayersIndexRoute: PlayersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
